services:
  ollama:
    profiles:
      - ollama-disabled

  task-app:
    environment:
      OLLAMA_BASE_URL: "http://host.docker.internal:11434"

  mcp-tools:
    environment:
      OLLAMA_BASE_URL: "http://host.docker.internal:11434"
